### ISSUE TITLE
Refactor the project

### ISSUE THREAD

**Issue by fernahh** [fernahh/imdbtr#16]
# Problems

### 1. Semantic
This module is a function that returns a movie from API provider. I think that must be renamed to `getMovie` or something like that.

### 2. The return value
When a movie it's not found, I return `false`. I think that is better just an empty object or array.

### 3. Unit tests
They got data from the server. Maybe is better just create mocks.

## helpers.js

This module is terrible. Just rewrites in a better way.

## bin/imdbtr

It's executable. Terrible too. It should just call the main module. We need to:

- remove the usage text;
- remove ugly conditionals.

## cli.js

Just remove. Completely unnecessary.

## imdbtr.js

The main module. It should just call helper functions, something like that:

```js
const getMovie = require('getMovie')(apiKey) // maybe create a npm module for that
const helpers = require('helpers')

const imdbtr = (params) => {
  getMovie(helpers.buildQueryParams(params))
    .then((data) => {
        console.log(helpers.formattedData(data))
    })
    .catch((error) => {
        console.error(error)
    })
}

module.exports = imdbtr
```

# Tasks

- [ ] Rewrite the api.js
- [ ] Rewrite the helpers.js
- [ ] Refactor the executable
- [ ] Remove cli.js
- [ ] Rewrite imdbtr.js
